name: Join Kubernetes Worker Node
description: Resets Kubernetes and joins the cluster using join command
inputs: {}
runs:
  using: "composite"
  steps:
    - name: Reset Kubernetes (clean slate)
      shell: bash
      run: |
        sudo kubeadm reset -f
        sudo rm -rf /etc/kubernetes/
        sudo rm -rf /var/lib/etcd/
        sudo rm -rf /var/lib/kubelet/*
        sudo rm -rf /etc/cni/net.d/
        sudo rm -rf /var/lib/cni/
        sudo rm -rf $HOME/.kube/
        sudo systemctl daemon-reexec
        sudo systemctl restart containerd
        sudo systemctl restart kubelet

    - name: Join Kubernetes cluster
      shell: bash
      run: |
        join_command=$(cat join_command.txt)
        echo "Running join command: $join_command"
        sudo $join_command
