name: Install Docker
description: Installs Docker on the runner machine
runs:
  using: "composite"
  steps:
    - name: Update APT and install Docker
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
