name: Docker Build & Push
description: Build frontend and backend Docker images and push to Docker Hub

inputs:
  dockerhub-username:
    description: 'Docker Hub username'
    required: true
  dockerhub-password:
    description: 'Docker Hub password'
    required: true

    
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      shell: bash
      run: |
        echo "${{ inputs.dockerhub-password }}" | sudo docker login -u "${{ inputs.dockerhub-username }}" --password-stdin

    - name: Build frontend image
      shell: bash
      run: |
        sudo docker build -t saravana227/frontend ./frontend

    - name: Push frontend image
      shell: bash
      run: |
        sudo docker push saravana227/frontend

    - name: Build backend image
      shell: bash
      run: |
        sudo docker build -t saravana227/backend ./backend

    - name: Push backend image
      shell: bash
      run: |
        sudo docker push saravana227/backend
