name: Install Helm
description: Installs Helm CLI
runs:
  using: "composite"
  steps:
    - name: Download and install Helm
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
