name: Kubernetes Environment Setup

on:
  push:
    branches:
      - develop

jobs:
  setup-k8s:
    name: Setup Docker and Kubernetes on Master Node
    runs-on: [self-hosted, master]

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Kubernetes Environment
        uses: ./custom-actions/kubernetes
