name: Ansible Provisioning

on:
  push:
    branches:
      - develop

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    name: Run Ansible to Setup Master and Worker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Keys
        run: |
          echo "${{ secrets.PEM_KEY }}" > master.pem
          echo "${{ secrets.PEM_KEY }}" > worker.pem
          chmod 600 master.pem worker.pem

      - name: Create Ansible Inventory File
        run: |
          mkdir -p ansible
          cat <<EOF > ansible/inventory.ini
[master]
${{ secrets.MASTER_IP }} ansible_user=${{ secrets.USER }} ansible_ssh_private_key_file=../master.pem

[worker]
${{ secrets.WORKER_IP }} ansible_user=${{ secrets.USER }} ansible_ssh_private_key_file=../worker.pem
EOF

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml
