name: CI/CD Pipeline

on:
  push:
    branches: [develop]


jobs:
  build-deploy:
    runs-on:  [self-hosted, master]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Docker Install Action
        uses: ./custom-actions/docker-install

      - name: Use Kubeadm Setup Action
        uses: ./custom-actions/kubeadm-setup

      - name: Use Helm Install Action
        uses: ./custom-actions/helm-install

      - name: Build Frontend Docker Image
        run: docker build -t frontend:latest ./frontend

      - name: Build Backend Docker Image
        run: docker build -t backend:latest ./backend

      - name: Deploy via Helmfile
        run: |
          cd helm
          helmfile apply

      - name: Check Frontend is Running
        run: curl -s http://localhost:30080/login || exit 1
